name: Android CI/CD

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for tags and commit hash

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Determine Version Name
        id: version
        shell: bash
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION_NAME=${GITHUB_REF#refs/tags/}
          else
            VERSION_NAME=$(git rev-parse --short HEAD)
          fi
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV
          echo "Version Name: $VERSION_NAME"

      - name: Decode Keystore
        if: ${{ env.SIGNING_KEY_STORE_BASE64 != '' }}
        run: |
          mkdir -p app
          echo "${{ secrets.SIGNING_KEY_STORE_BASE64 }}" | base64 --decode > app/keystore.jks
        env:
          SIGNING_KEY_STORE_BASE64: ${{ secrets.SIGNING_KEY_STORE_BASE64 }}

      - name: Build with Gradle
        run: ./gradlew assembleDebug assembleRelease -Pandroid.injected.version.code=${{ github.run_number }} -Pandroid.injected.version.name=${{ env.VERSION_NAME }}
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Upload Debug Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QRCodeShare-debug-${{ env.VERSION_NAME }}
          path: composeApp/build/outputs/apk/debug/*.apk

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v4
        with:
          name: QRCodeShare-release-${{ env.VERSION_NAME }}
          path: composeApp/build/outputs/apk/release/*.apk

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            composeApp/build/outputs/apk/release/*.apk
            composeApp/build/outputs/apk/debug/*.apk
          generate_release_notes: true

